import repositories.member_repository as member_repository
import repositories.gym_class_repository as gym_class_repository
import repositories.instructor_repository as instructor_repository
import repositories.attendance_repository as attendance_repository
import repositories.location_repository as location_repository
from models.member import Member
from models.gym_class import GymClass
from models.instructor import Instructor
from models.attendance import Attendance
from models.location import Location

attendance_repository.delete_all()
member_repository.delete_all()
gym_class_repository.delete_all()
instructor_repository.delete_all()
location_repository.delete_all()


member_1 = Member("Stuart", "McAra", '1989-03-26', "Peak")
member_2 = Member("Michael", "Scott", '1965-12-03', "Off Peak")
member_3 = Member("Samwise", "Arbroath", '1974-12-09', "Peak")
member_4 = Member("Alistair", "Biscuit", '1945-07-02', "Peak")
member_5 = Member("Alice", "Thumbsniffer", '2001-01-14', "Off Peak")
member_6 = Member("Tom", "Chief", '2004-8-03', "Off Peak")
member_7 = Member("Annabelle", "Davidson", '1999-02-01', "Peak")
member_8 = Member("Nikki", "Farthing", '1986-11-30', "Peak")
member_9 = Member("Brian", "Forsyth", '1901-01-31', "Peak")
member_10 = Member("David", "Fortesque", '1956-12-28', "Peak")
member_11 = Member("Deirdre", "McMackinson", '1979-10-07', "Off Peak")
member_12 = Member("Creepy", "Joe", '1965-12-03', "Peak")
member_13 = Member("Jennifer", "Longbottom", '1960-07-18', "Off Peak")
member_14 = Member("Elvis", "Measley", '1942-12-02', "Peak")
member_15 = Member("Janet", "Brixton", '1967-11-21', "Off Peak")
member_16 = Member("Henry", "Nostrilbreather", '1993-06-12', "Peak")
member_16 = Member("Elspeth", "Pennythwaite", '1990-12-28', "Off Peak")

member_repository.save(member_1)
member_repository.save(member_2)
member_repository.save(member_3)
member_repository.save(member_4)
member_repository.save(member_5)
member_repository.save(member_6)
member_repository.save(member_7)
member_repository.save(member_8)
member_repository.save(member_9)
member_repository.save(member_10)
member_repository.save(member_11)
member_repository.save(member_12)
member_repository.save(member_13)
member_repository.save(member_14)
member_repository.save(member_15)
member_repository.save(member_16)


instructor_1 = Instructor("Big Jayne")
instructor_2 = Instructor("Bendy Jo")
instructor_3 = Instructor("Timmy Muscles")
instructor_4 = Instructor("Quads Etherington")
instructor_5 = Instructor("Old man Johnson")
instructor_6 = Instructor("Mickey the Fist")

instructor_repository.save(instructor_1)
instructor_repository.save(instructor_2)
instructor_repository.save(instructor_3)
instructor_repository.save(instructor_4)
instructor_repository.save(instructor_5)
instructor_repository.save(instructor_6)


location_1 = Location("Free Weights Gym", 15)
location_2 = Location("Yoga Studio", 10)
location_3 = Location("Boxing Gym", 12)
location_4 = Location("Cycling Studio", 20)
location_5 = Location("Swimming Pool", 20)
location_6 = Location("Dance Studio", 20)

location_repository.save(location_1)
location_repository.save(location_2)
location_repository.save(location_3)
location_repository.save(location_4)
location_repository.save(location_5)
location_repository.save(location_6)


class_1 = GymClass("Bodybuilding", instructor_3, "2021-03-25", "14:00", 90, location_1)
class_2 = GymClass("Yoga", instructor_2, "2021-03-27", "13:30", 60, location_2)
class_3 = GymClass("Spin", instructor_6, "2021-03-26", "09:00", 45, location_4)
class_4 = GymClass("Swimming", instructor_5, "2021-03-25", "08:30", 60, location_5)
class_5 = GymClass("Body Pump", instructor_2, "2021-03-26", "18:00", 60, location_6)
class_6 = GymClass("Cardio", instructor_3, "2021-03-25", "17:30", 60, location_6)
class_7 = GymClass("Zumba", instructor_2, "2021-03-27", "19:30", 60, location_6)
class_8 = GymClass("Bodybuilding 2", instructor_1, "2021-03-28", "12:30", 60, location_1)
class_9 = GymClass("Kickboxing", instructor_6, "2021-03-27", "10:00", 60, location_3)
class_10 = GymClass("Boxing", instructor_2, "2021-03-27", "07:45", 90, location_3)
class_11 = GymClass("Jiu Jitsu", instructor_4, "2021-03-26", "11:00", 60, location_3)
class_12 = GymClass("Yoga 2", instructor_2, "2021-03-25", "19:30", 30, location_2)
class_13 = GymClass("Pilates", instructor_2, "2021-03-25", "14:30", 45, location_2)
class_13 = GymClass("Weightlifting Technique", instructor_4, "2021-03-25", "15:00", 60, location_1)

gym_class_repository.save(class_1)
gym_class_repository.save(class_2)
gym_class_repository.save(class_3)
gym_class_repository.save(class_4)
gym_class_repository.save(class_5)
gym_class_repository.save(class_6)
gym_class_repository.save(class_7)
gym_class_repository.save(class_8)
gym_class_repository.save(class_9)
gym_class_repository.save(class_10)
gym_class_repository.save(class_11)
gym_class_repository.save(class_12)
gym_class_repository.save(class_13)


attendance_1 = Attendance(class_1, member_1)
attendance_2 = Attendance(class_2, member_2)
attendance_3 = Attendance(class_3, member_4)
attendance_4 = Attendance(class_4, member_8)
attendance_5 = Attendance(class_5, member_6)
attendance_6 = Attendance(class_6, member_8)
attendance_7 = Attendance(class_7, member_8)
attendance_8 = Attendance(class_8, member_9)
attendance_9 = Attendance(class_9, member_10)
attendance_10 = Attendance(class_10, member_15)
attendance_11 = Attendance(class_11, member_14)
attendance_12 = Attendance(class_12, member_13)
attendance_13 = Attendance(class_13, member_12)
attendance_14 = Attendance(class_12, member_16)
attendance_15 = Attendance(class_11, member_12)
attendance_16 = Attendance(class_13, member_10)
attendance_17 = Attendance(class_1, member_8)
attendance_18 = Attendance(class_2, member_7)
attendance_19 = Attendance(class_3, member_7)
attendance_20 = Attendance(class_4, member_6)
attendance_21 = Attendance(class_5, member_4)
attendance_22 = Attendance(class_6, member_5)
attendance_23 = Attendance(class_7, member_6)
attendance_24 = Attendance(class_7, member_7)
attendance_25 = Attendance(class_8, member_2)
attendance_26 = Attendance(class_9, member_3)
attendance_27 = Attendance(class_10, member_4)
attendance_28 = Attendance(class_7, member_1)

attendance_repository.save(attendance_1)
attendance_repository.save(attendance_2)
attendance_repository.save(attendance_3)
attendance_repository.save(attendance_4)
attendance_repository.save(attendance_5)
attendance_repository.save(attendance_6)
attendance_repository.save(attendance_7)
attendance_repository.save(attendance_8)
attendance_repository.save(attendance_9)
attendance_repository.save(attendance_10)
attendance_repository.save(attendance_11)
attendance_repository.save(attendance_12)
attendance_repository.save(attendance_13)
attendance_repository.save(attendance_14)
attendance_repository.save(attendance_15)
attendance_repository.save(attendance_16)
attendance_repository.save(attendance_17)
attendance_repository.save(attendance_18)
attendance_repository.save(attendance_19)
attendance_repository.save(attendance_20)
attendance_repository.save(attendance_21)
attendance_repository.save(attendance_22)
attendance_repository.save(attendance_23)
attendance_repository.save(attendance_24)
attendance_repository.save(attendance_25)
attendance_repository.save(attendance_26)
attendance_repository.save(attendance_27)
attendance_repository.save(attendance_28)

